### ISSUE TITLE
Umlauts disappear in code examples

### ISSUE THREAD

**Issue by wehro** [cgnieder/cnltx#3]
```
\documentclass{article}
\usepackage{cnltx-example}
\begin{document}
\begin{example}
  aäoöuüß
\end{example}
\end{document}
```
The output of this example is `aou`, even if compiled with *xelatex* oder *lualatex*. The umlauts should not disappear.

**Comment by cgnieder** [comment]
Well, the package does

```latex
  literate         =
    {ä}{{\"a}}{1}
    {ö}{{\"o}}{1}
    {ü}{{\"u}}{1}
    {Ä}{{\"A}}{1}
    {Ö}{{\"O}}{1}
    {Ü}{{\"U}}{1}
    {ß}{{\ss}}{1} ,
```
which is the cause for the missing umlauts in the typeset example. But see what happens if it doesn't:

```latex
\documentclass{article}
\usepackage{cnltx-example}
\begin{document}
\begin{example}[add-listings-options={literate=}]
  aäoöuüß
\end{example}
\end{document}
```

I have no solution for this…

**Comment by wehro** [comment]
Oh, despite Unicode, the Babylonian language confusion never seems to end within the world of computers. This is a pity.
But thank you, anyway.

**Comment by wehro** [comment]
Trying umlauts again in code examples, I found that the issue is still there. But the example mentioned above works with XeLaTeX and LuaLaTeX if the `literate` option is removed from the package code. So it’s probably better to leave it out.
