### ISSUE TITLE
Inside for outside

### ISSUE THREAD

**Issue by koppor** [cgnieder/cnltx#4]
I'd like to typeset a floating environment inside the `example` environment. I am aware that the option `outside=true` is recommended. But then, the result is typeset outside the box, but I want it inside.

MWE:

```latex
\documentclass{article}

\usepackage{cleveref}
\usepackage{cnltx-example}

\begin{document}

\listoffigures

\begin{figure}[t]
    fig1
    \caption{fig1}
    \label{fig1}
\end{figure}

Are you fig1, \cref{fig1}?

\begin{example}[outside=false]
  \listoffigures

  \begin{figure}
  fig2
  \caption{fig2}
  \label{fig2}
  \end{figure}
  Are you fig2, \cref{fig2}?
  \ref{fig2}
\end{example}

\begin{figure}[b]
    fig3
    \caption{fig3}
    \label{fig3}
\end{figure}

Are you fig3, \cref{fig3}?

\end{document}
```

Note that [examplep](https://ctan.org/pkg/examplep) supports that. However, the output is not as nice as the one from cnltx-example. Moreover, that package is unmaintained.

This is what examplep outputs:

![grafik](https://user-images.githubusercontent.com/1366654/81235584-9b1aa780-8ffb-11ea-8a59-909fdc35c210.png)

No worries if that feature cannot be implemented here. Then, I'll find worarounds. Such as using [standalone](https://ctan.org/pkg/standalone?lang=de) for the small number of examples where I could need it. (Maybe, there will be many examples, because I'd like to have all figures with captions as LaTeX examples - including tikz-examples, ... Reason: beginner's tend to copy-and-paste without much thinking.)

Background for my question: I am working on a document targeted for LaTeX novices who are IMHO more practised in reading PDFs files than having a LaTeX source and then seeing the rendered output on a PDF file. Since everything is new to them, I really aim for the side-by-side comparison.

**Comment by cgnieder** [comment]
Well, the only way to have a float inside is to make it *not* float. That is the example environment needs to patch the float mechanism (or just the `figure` and `table` environments) and more or less disable them. This is exactly what `examplep` does. The code below is a copy of what `examplep` does adapted for `cnltx-example`:

```latex
\documentclass{article}

\usepackage{cleveref}
\usepackage[example]{cnltx}

\makeatletter
\newcommand*\fakefloatbegin[1]{%
  \def\@captype{#1}%
  \vskip\intextsep
  \color@vbox
    \normalcolor
    \vbox \bgroup
      \hsize\columnwidth
      \@parboxrestore
      \@floatboxreset
}
\newcommand*\fakefloatend{\@endfloatbox\vskip\intextsep}

\setcnltx{
  add-cmds = {listoffigures} ,
  pre-code={%
    \renewenvironment{figure}[1][]{\fakefloatbegin{figure}}{\fakefloatend}%
  }
}

\begin{document}

\listoffigures

\begin{figure}[t]
    fig1
    \caption{fig1}
    \label{fig1}
\end{figure}

Are you fig1, \cref{fig1}?

\begin{example}
  \listoffigures

  \begin{figure}
  fig2
  \caption{fig2}
  \label{fig2}
  \end{figure}
  Are you fig2, \cref{fig2}?
  \ref{fig2}
\end{example}

\begin{figure}[b]
    fig3
    \caption{fig3}
    \label{fig3}
\end{figure}

Are you fig3, \cref{fig3}?

\end{document}
```

**Comment by cgnieder** [comment]
Having another list of figures in the document would be more tricky…

**Comment by koppor** [comment]
> Having another list of figures in the document would be more tricky…

There is no (real) need for support of nested `\listoflistings`.

**Comment by koppor** [comment]
> Well, the only way to have a float inside is to make it _not_ float. That is the example environment needs to patch the float mechanism (or just the `figure` and `table` environments) and more or less disable them. 

Agree.

> This is exactly what `examplep` does. The code below is a copy of what `examplep` does adapted for `cnltx-example`:

The difference is that the float inside is numbered in the context of the outer floats. It also increases the float counter.

Would it be possible to have it independent? I.e., starting from 1? As if it was a new "document"? (See the examplep output 😇 )

![grafik](https://user-images.githubusercontent.com/1366654/81317476-3019b100-908d-11ea-859f-13eee0a9ddd2.png)

**Comment by cgnieder** [comment]
Try

```latex
\makeatletter
\newcommand*\expl@fakefloatbegin[1]{%
  \def\@captype{#1}%
  \vskip\intextsep
  \color@vbox
    \normalcolor
    \vbox \bgroup
      \hsize\columnwidth
      \@parboxrestore
      \@floatboxreset
}
\newcommand*\expl@fakefloatend{\@endfloatbox\vskip\intextsep}

\newcommand*\expl@resetcounter[1]{%
  \ifstrequal{#1}{page}{}{\setcounter{#1}{0}}%
}

\setcnltx{
  add-cmds = {listoffigures} ,
  pre-code={%
    \let\addtocontents\@gobbletwo
    \let\@elt\expl@resetcounter \cl@@ckpt
    \renewenvironment{figure}[1][]{\expl@fakefloatbegin{figure}}{\expl@fakefloatend}%
  }
}
\makeatother
```

**Comment by cgnieder** [comment]
I take it this is resolved?

**Comment by koppor** [comment]
The result looks awesome:

![grafik](https://user-images.githubusercontent.com/1366654/82147137-05c6b100-984e-11ea-9e8e-b21b641c6260.png)

**Comment by koppor** [comment]
Could that be added to the package code?

**Comment by koppor** [comment]
I was happy too early - the numbering is smashed. Could you have a look?

![grafik](https://user-images.githubusercontent.com/1366654/82844427-b3862f80-9ee0-11ea-87ad-bbdb2a7752cd.png)

MWE:

```latex
\documentclass{book}

\usepackage{cleveref}
\usepackage{cnltx-example}

\makeatletter
\newcommand*\expl@fakefloatbegin[1]{%
  \def\@captype{#1}%
  \vskip\intextsep
  \color@vbox
    \normalcolor
    \vbox \bgroup
      \hsize\columnwidth
      \@parboxrestore
      \@floatboxreset
}
\newcommand*\expl@fakefloatend{\@endfloatbox\vskip\intextsep}

\newcommand*\expl@resetcounter[1]{%
  \ifstrequal{#1}{page}{}{\setcounter{#1}{0}}%
}

\setcnltx{
  add-cmds = {listoffigures} ,
  pre-code={%
    \let\addtocontents\@gobbletwo
    \let\@elt\expl@resetcounter \cl@@ckpt
    \renewenvironment{figure}[1][]{\expl@fakefloatbegin{figure}}{\expl@fakefloatend}%
  }
}
\makeatother

\begin{document}

\chapter{Chapter 1}

\listoffigures

\section{Section 1}

\begin{figure}[t]
    fig1
    \caption{fig1}
    \label{fig1}
\end{figure}

Are you fig1, \cref{fig1}? You should be nubmer 1.

\begin{example}[outside=false,code-left=false]

  \begin{figure}
  fig2
  \caption{fig2}
  \label{fig2}
  \end{figure}
  Are you fig2, \cref{fig2}? You should be number 1.
  \ref{fig2}
\end{example}

\section{Section 2}

\begin{figure}[b]
    fig3
    \caption{fig3}
    \label{fig3}
\end{figure}

Are you fig3, \cref{fig3}? You should be number 2.

\end{document}
```
