### ISSUE TITLE
Output before code

### ISSUE THREAD

**Issue by koppor** [cgnieder/cnltx#6]
There is the option `code-left`. Is there an option `code-first` (default: `true`)?

I would like to have the typeset output first and then the source in the `example` environment. For the `side-by-side` option, there is an equivalent option: `code-left=false` leads that the output is on the left (and not on the right).

MWE:

```latex
\documentclass{article}
\usepackage{cnltx-example}
\begin{document}
\begin{example}[code-first=false]
Test
\end{example}
\end{document}
```

Output:

![grafik](https://user-images.githubusercontent.com/1366654/82776774-52ad1780-9e4c-11ea-913d-dbf06bc6a14d.png)

**Comment by cgnieder** [comment]
No, there is no such option.

**Comment by koppor** [comment]
A wonderful good morning 🌞 

Could you please add support for one? 🌮 😄
