### ISSUE TITLE
Undefined \@EverySelectfont@EveryHook

### ISSUE THREAD

**Issue by joneppie** [cgnieder/cnltx#9]
Every document I try to translate with `cnltx` gives me the following error with the latest version of TexLive:

    ! Undefined control sequence.
    \@EverySelectfont@EveryHook ...oe@everyselectfont

**Comment by cgnieder** [comment]
`cnltx` needs some fixes. I've just committed my local version which runs without errors on an up to date texlive. I'll probably update some working version to CTAN in the near future.

**Comment by joneppie** [comment]
It works, thanks.
